# Generated by Django 4.0.4 on 2023-03-10 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Codigo Producto')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre Producto')),
                ('descripcion', models.TextField(max_length=250, verbose_name='Descripcion Producto')),
                ('precio', models.IntegerField(default=0, verbose_name='Precio Producto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DetalleProductos',
            fields=[
                ('idDetalleProducto', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Detalle Producto')),
                ('cantidad', models.IntegerField(default=0, verbose_name='Cantidad Producto')),
                ('valorTotal', models.FloatField(verbose_name='Valor Total')),
                ('ValorIva', models.FloatField(verbose_name='Valor IVA')),
                ('idProducto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Api.productos', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Detalle del Producto',
                'verbose_name_plural': 'Detalles de Productos',
                'ordering': ['idProducto'],
            },
        ),
    ]
