# Generated by Django 4.0.4 on 2023-03-11 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleproductos',
            name='ValorIva',
            field=models.FloatField(blank=True, null=True, verbose_name='Valor IVA'),
        ),
        migrations.AlterField(
            model_name='detalleproductos',
            name='cantidad',
            field=models.IntegerField(default=1, verbose_name='Cantidad Producto'),
        ),
        migrations.AlterField(
            model_name='detalleproductos',
            name='idProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.productos', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='detalleproductos',
            name='valorTotal',
            field=models.FloatField(blank=True, null=True, verbose_name='Valor Total'),
        ),
    ]
