# Generated by Django 4.0.4 on 2023-03-11 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_alter_detalleproductos_valoriva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleproductos',
            name='valorIva',
            field=models.FloatField(blank=True, default=0, verbose_name='Valor IVA'),
        ),
        migrations.AlterField(
            model_name='detalleproductos',
            name='valorTotal',
            field=models.FloatField(blank=True, default=0, verbose_name='Valor Total'),
        ),
    ]
